"""phase5 technique_stat bandit memory

Revision ID: 0c960bf51bc5
Revises: 8f88ef9f21f4
Create Date: 2026-06-11 23:52:01.769195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c960bf51bc5'
down_revision: Union[str, Sequence[str], None] = '8f88ef9f21f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('techniquestat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('technique_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_disc', sa.Float(), nullable=False),
    sa.Column('s_disc', sa.Float(), nullable=False),
    sa.Column('raw_count', sa.Integer(), nullable=False),
    sa.Column('raw_successes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('objective_slug', 'technique_slug', name='uq_objtech_stat')
    )
    op.create_index(op.f('ix_techniquestat_objective_slug'), 'techniquestat', ['objective_slug'], unique=False)
    op.create_index(op.f('ix_techniquestat_technique_slug'), 'techniquestat', ['technique_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_techniquestat_technique_slug'), table_name='techniquestat')
    op.drop_index(op.f('ix_techniquestat_objective_slug'), table_name='techniquestat')
    op.drop_table('techniquestat')
    # ### end Alembic commands ###
