"""phase7 governance audit + ingestion record

Revision ID: 2ddc53662209
Revises: 0c960bf51bc5
Create Date: 2026-06-12 00:50:49.066422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ddc53662209'
down_revision: Union[str, Sequence[str], None] = '0c960bf51bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prev_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entry_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditevent_event_type'), 'auditevent', ['event_type'], unique=False)
    op.create_index(op.f('ix_auditevent_run_id'), 'auditevent', ['run_id'], unique=False)
    op.create_table('ingestionrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quote', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestionrecord_objective_slug'), 'ingestionrecord', ['objective_slug'], unique=False)
    op.add_column('run', sa.Column('roe', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('run', sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('run', sa.Column('approved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'approved_at')
    op.drop_column('run', 'approved_by')
    op.drop_column('run', 'roe')
    op.drop_index(op.f('ix_ingestionrecord_objective_slug'), table_name='ingestionrecord')
    op.drop_table('ingestionrecord')
    op.drop_index(op.f('ix_auditevent_run_id'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_event_type'), table_name='auditevent')
    op.drop_table('auditevent')
    # ### end Alembic commands ###
