"""objective catalog (spine + crosswalk + technique stubs)

Revision ID: 5d4bc84aaf8f
Revises: ffc489e27bc6
Create Date: 2026-06-11 22:41:09.635636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d4bc84aaf8f'
down_revision: Union[str, Sequence[str], None] = 'ffc489e27bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frameworkcontrol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('control_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('citation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework', 'control_id', name='uq_framework_control')
    )
    op.create_index(op.f('ix_frameworkcontrol_control_id'), 'frameworkcontrol', ['control_id'], unique=False)
    op.create_index(op.f('ix_frameworkcontrol_framework'), 'frameworkcontrol', ['framework'], unique=False)
    op.create_table('objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('family', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_pillar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('testability', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success_definition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oracle_hint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provenance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spine_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objective_mode'), 'objective', ['mode'], unique=False)
    op.create_index(op.f('ix_objective_primary_pillar'), 'objective', ['primary_pillar'], unique=False)
    op.create_index(op.f('ix_objective_slug'), 'objective', ['slug'], unique=True)
    op.create_index(op.f('ix_objective_status'), 'objective', ['status'], unique=False)
    op.create_table('objectivecontrolmap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('framework', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('control_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objectivecontrolmap_control_id'), 'objectivecontrolmap', ['control_id'], unique=False)
    op.create_index(op.f('ix_objectivecontrolmap_framework'), 'objectivecontrolmap', ['framework'], unique=False)
    op.create_index(op.f('ix_objectivecontrolmap_objective_slug'), 'objectivecontrolmap', ['objective_slug'], unique=False)
    op.create_table('objectivetechniquemap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('technique_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiers', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objectivetechniquemap_objective_slug'), 'objectivetechniquemap', ['objective_slug'], unique=False)
    op.create_index(op.f('ix_objectivetechniquemap_technique_slug'), 'objectivetechniquemap', ['technique_slug'], unique=False)
    op.create_table('technique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('technique_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technique_slug'), 'technique', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technique_slug'), table_name='technique')
    op.drop_table('technique')
    op.drop_index(op.f('ix_objectivetechniquemap_technique_slug'), table_name='objectivetechniquemap')
    op.drop_index(op.f('ix_objectivetechniquemap_objective_slug'), table_name='objectivetechniquemap')
    op.drop_table('objectivetechniquemap')
    op.drop_index(op.f('ix_objectivecontrolmap_objective_slug'), table_name='objectivecontrolmap')
    op.drop_index(op.f('ix_objectivecontrolmap_framework'), table_name='objectivecontrolmap')
    op.drop_index(op.f('ix_objectivecontrolmap_control_id'), table_name='objectivecontrolmap')
    op.drop_table('objectivecontrolmap')
    op.drop_index(op.f('ix_objective_status'), table_name='objective')
    op.drop_index(op.f('ix_objective_slug'), table_name='objective')
    op.drop_index(op.f('ix_objective_primary_pillar'), table_name='objective')
    op.drop_index(op.f('ix_objective_mode'), table_name='objective')
    op.drop_table('objective')
    op.drop_index(op.f('ix_frameworkcontrol_framework'), table_name='frameworkcontrol')
    op.drop_index(op.f('ix_frameworkcontrol_control_id'), table_name='frameworkcontrol')
    op.drop_table('frameworkcontrol')
    # ### end Alembic commands ###
