"""phase4 technique fields + persona + attempt technique/persona/csrt

Revision ID: 8f88ef9f21f4
Revises: fabd81d9e968
Create Date: 2026-06-11 23:15:55.782496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f88ef9f21f4'
down_revision: Union[str, Sequence[str], None] = 'fabd81d9e968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attributes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_slug'), 'persona', ['slug'], unique=True)
    op.create_index(op.f('ix_persona_status'), 'persona', ['status'], unique=False)
    op.add_column('attempt', sa.Column('technique_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('attempt', sa.Column('persona_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('attempt', sa.Column('csrt', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_attempt_technique_slug'), 'attempt', ['technique_slug'], unique=False)
    op.add_column('technique', sa.Column('strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('technique', sa.Column('phase_plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('technique', sa.Column('applicable_modes', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('technique', sa.Column('modifiers', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('technique', sa.Column('provenance', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('technique', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='active'))
    op.create_index(op.f('ix_technique_status'), 'technique', ['status'], unique=False)
    op.drop_column('technique', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technique', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_technique_status'), table_name='technique')
    op.drop_column('technique', 'status')
    op.drop_column('technique', 'provenance')
    op.drop_column('technique', 'modifiers')
    op.drop_column('technique', 'applicable_modes')
    op.drop_column('technique', 'phase_plan')
    op.drop_column('technique', 'strategy')
    op.drop_index(op.f('ix_attempt_technique_slug'), table_name='attempt')
    op.drop_column('attempt', 'csrt')
    op.drop_column('attempt', 'persona_slug')
    op.drop_column('attempt', 'technique_slug')
    op.drop_index(op.f('ix_persona_status'), table_name='persona')
    op.drop_index(op.f('ix_persona_slug'), table_name='persona')
    op.drop_table('persona')
    # ### end Alembic commands ###
