"""attempt objective_slug

Revision ID: fabd81d9e968
Revises: 5d4bc84aaf8f
Create Date: 2026-06-11 22:51:33.892423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fabd81d9e968'
down_revision: Union[str, Sequence[str], None] = '5d4bc84aaf8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('objective_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.create_index(op.f('ix_attempt_objective_slug'), 'attempt', ['objective_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_objective_slug'), table_name='attempt')
    op.drop_column('attempt', 'objective_slug')
    # ### end Alembic commands ###
