"""attempt verdict fields

Revision ID: ffc489e27bc6
Revises: d85d0af991aa
Create Date: 2026-06-11 21:46:30.522471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ffc489e27bc6'
down_revision: Union[str, Sequence[str], None] = 'd85d0af991aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('verdict_score', sa.Float(), nullable=False, server_default='0'))
    op.add_column('attempt', sa.Column('judge_votes', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('attempt', sa.Column('detector_hits', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt', 'detector_hits')
    op.drop_column('attempt', 'judge_votes')
    op.drop_column('attempt', 'verdict_score')
    # ### end Alembic commands ###
